### ISSUE TITLE
Client send request quota with old token

### ISSUE THREAD

**Issue by emli** [marcoarthur/gorjun-perl-cli#2]
![image](https://user-images.githubusercontent.com/5517490/34555442-0b88f44a-f15c-11e7-96ba-6ed911f15ca9.png)

After 
1)Server shutdowned
2)Database cleaned
3)Register User

![image](https://user-images.githubusercontent.com/5517490/34555499-5d54e14e-f15c-11e7-9694-d0bf2fddb695.png)

4) Client trying get `quota` with old token as you can see from second screenshot 

[Test results](https://gist.github.com/emli/d6abadf5eb4bfcc15bb8a2cb5c2d96b2)
  
**UPD**
![image](https://user-images.githubusercontent.com/5517490/34556589-1ac99ffe-f161-11e7-9ca3-a26bccb3acc6.png)

I am trying get token first , but backend getting old token

**Comment by emli** [comment]
Today I tried see exactly request url, found

![image](https://user-images.githubusercontent.com/5517490/34714720-881be70a-f554-11e7-86be-47bf2cc3cc22.png)

Here client sending lot of tokens as parameter

**Comment by marcoarthur** [comment]
the branch https://github.com/marcoarthur/gorjun-perl-cli/tree/dev-fork has the patch for it, you can test it, then we merge it

**Comment by emli** [comment]
Fixed

**Comment by akarasulu** [comment]
Guys please try to move conversations and the software over to the Subutai Gorjun repository. It helped get started in the beginning but it's leading to entropy now. Let's consolidate back into the main line. You guys own it now anyways :).
