### ISSUE TITLE
How to reproduce this error?

### ISSUE THREAD

**Issue by emli** [marcoarthur/gorjun-perl-cli#4]
# 
******************************************************************************** at /home/itaipu/tools/perl5/gorjun/t/test_cover.t line 56.
* Cound't finish all tests to cover module: apt at /home/itaipu/tools/perl5/gorjun/t/test_cover.t line 57.
* Test gave: Error sending request to http://127.0.0.1:8080/kurjun/rest/auth/register Got this: Connection refused
 at t/test.t line 49.
******************************************************************************** at /home/itaipu/tools/perl5/gorjun/t/test_cover.t line 59.

**Comment by marcoarthur** [comment]
That is because gorjun can't handle too much connections. But we are investigating better
